package tup.simple.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import tup.simple.models.departamentos;
import tup.simple.repositories.departamentosRepository;

@Controller // This means that this class is a Controller
// La URL que vaya en la anotación habrá que agregarla detrás del puerto :8080
// en todas las llamadas a esta aplicación.
// Por ejemplo @RequestMapping("/user") resultaría en lo siguiente:
// localhost:8080/anime.... y detrás de esto habría que agregar el
// resto de la URL.
// En este caso, no necesitamos nada, y queda simplemente localhost:8080
@RequestMapping("/departamentos")
public class departamentosController {
    // This means to get the bean called userRepository
    // which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private departamentosRepository _deptosRepository;

    @PostMapping("/add") // Map ONLY POST Requests
    public @ResponseBody String addNewDepto(@RequestParam String nombredpto, @RequestParam String ciudad,
    @RequestParam Long coddirector) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        departamentos n = new departamentos();
        n.setNombredpto(nombredpto);
        n.setCiudad(ciudad);
        n.setCoddirector(coddirector);
        _deptosRepository.save(n);
        return "Saved";
    }

    @PostMapping("/delete/{id}") // Map ONLY POST Requests
    public @ResponseBody String deleteDeptoById(@PathVariable Long coddpto) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        _deptosRepository.deleteById(coddpto);
        return "Deleted";
    }

    @GetMapping("/all")
    public @ResponseBody String getAllDeptos() {
        // This returns a JSON or XML with the users
        Iterable<departamentos> iterable = _deptosRepository.findAll();
        String resp = "<style>\n"
                +"#users {\n"
                +"  font-family: Arial, Helvetica, sans-serif;\n"
                +"  border-collapse: collapse;\n"
                +"  width: 100%;}\n"

                +"#users td, #users th {\n"
                +"  border: 1px solid #ddd;\n"
                +"  padding: 8px;}\n"

                +"#users tr:nth-child(even){background-color: #f2f2f2;}\n"

                +"#users tr:hover {background-color: #ddd;}\n"

                +"#users th {\n"
                +"  padding-top: 12px;\n"
                +"  padding-bottom: 12px;\n"
                +"  text-align: left;\n"
                +"  background-color: #04AA6D;\n"
                +"  color: white;}\n"
                +"</style>";
        resp += "<table id ='users'>"
                + "<tr>"
                + "<th>Codigo depto</th>"
                + "<th>Nombre departamento</th>"
                + "<th>Ciudad</th>"
                + "<th>Codigo Director</th>"
                + "</tr>";
        // No puedo usar forEach() con una función lambda
        // porque el scope de las variables no lo permite.
        for (departamentos deptos : iterable) {
            resp += "<tr>"
                    + "<td>" + deptos.getCoddpto() + "</td>"
                    + "<td>" + deptos.getNombredpto() + "</td>"
                    + "<td>" + deptos.getCiudad() + "</td>"
                    + "<td>" + deptos.getCoddirector() + "</td>"
                    + "</tr>";
        }
        return resp + "</table>";
    }

    @GetMapping("")
    public @ResponseBody String hola() {
        return "Hola";
    }
}
